[2024-05-30 03:58:58,939][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\data_loader\creator.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mean'] = (df['Low'] + df['High']) / 2

[2024-05-30 03:59:10,228][factory.trainer][INFO] - Training started.
[2024-05-30 03:59:12,073][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\test\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

[2024-05-30 03:59:12,318][factory.trainer][INFO] - ----------------------------------------------------------------------------------------------------
[2024-05-30 03:59:12,319][factory.trainer][INFO] - Training is completed in 2.09 seconds.
[2024-05-30 03:59:12,320][factory.evaluator][INFO] - Evaluating started.
[2024-05-30 03:59:12,339][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\utils\reporter.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.df_of_cross_validation.iloc[self.counter_cross_validation][metric_name] = value

[2024-05-30 03:59:12,343][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\utils\reporter.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.df_of_cross_validation.iloc[self.counter_cross_validation][metric_name] = value

[2024-05-30 03:59:12,349][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\utils\reporter.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.df_of_cross_validation.iloc[self.counter_cross_validation][metric_name] = value

[2024-05-30 03:59:12,353][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\utils\reporter.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.df_of_cross_validation.iloc[self.counter_cross_validation][metric_name] = value

[2024-05-30 03:59:12,758][factory.profit_calculator][INFO] - Low price training started.
[2024-05-30 03:59:12,761][factory.trainer][INFO] - Training started.
[2024-05-30 03:59:14,519][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\test\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

[2024-05-30 03:59:14,738][factory.trainer][INFO] - ----------------------------------------------------------------------------------------------------
[2024-05-30 03:59:14,738][factory.trainer][INFO] - Training is completed in 1.98 seconds.
[2024-05-30 03:59:14,753][factory.profit_calculator][INFO] - High price training started.
[2024-05-30 03:59:14,756][factory.trainer][INFO] - Training started.
[2024-05-30 03:59:17,778][py.warnings][WARNING] - D:\hoc\Code\cryptopredictions\crypto-prediction\test\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

[2024-05-30 03:59:18,005][factory.trainer][INFO] - ----------------------------------------------------------------------------------------------------
[2024-05-30 03:59:18,005][factory.trainer][INFO] - Training is completed in 3.25 seconds.
